import os
import pandas as pd
import streamlit as st


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Demand Forecasting Dashboard",
    page_icon="📈",
    layout="wide"
)


# ============================================================
# PATHS
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

PREDICTIONS_PATH = os.path.join(
    BASE_DIR,
    "data",
    "forecasts",
    "final_evaluation",
    "final_predictions.csv"
)

MODEL_COMPARISON_PATH = os.path.join(
    BASE_DIR,
    "data",
    "forecasts",
    "model_comparison.csv"
)

STORE_PERFORMANCE_PATH = os.path.join(
    BASE_DIR,
    "data",
    "forecasts",
    "final_evaluation",
    "store_performance.csv"
)

FAMILY_PERFORMANCE_PATH = os.path.join(
    BASE_DIR,
    "data",
    "forecasts",
    "final_evaluation",
    "family_performance.csv"
)

MONTHLY_PERFORMANCE_PATH = os.path.join(
    BASE_DIR,
    "data",
    "forecasts",
    "final_evaluation",
    "monthly_performance.csv"
)

OVERALL_METRICS_PATH = os.path.join(
    BASE_DIR,
    "data",
    "forecasts",
    "final_evaluation",
    "overall_metrics.csv"
)


# ============================================================
# TITLE
# ============================================================

st.title("📈 Demand Forecasting Dashboard")

st.markdown(
    """
    ### Store Sales Demand Forecasting

    This dashboard presents predictions generated by the
    **tuned LightGBM demand forecasting model**.

    The model was trained using historical sales, promotions,
    store information, oil prices, holidays and time-series
    features.
    """
)


# ============================================================
# LOAD DATA
# ============================================================

@st.cache_data
def load_predictions():

    df = pd.read_csv(
        PREDICTIONS_PATH
    )
# Map prediction file columns to dashboard-friendly names
    df["actual_sales"] = df["sales"]
    df["predicted_sales"] = df["prediction"]
    df["date"] = pd.to_datetime(
        df["date"]
    )

    return df


@st.cache_data
def load_csv(path):

    if not os.path.exists(path):
        return None

    return pd.read_csv(path)


# ============================================================
# CHECK FILE
# ============================================================

if not os.path.exists(PREDICTIONS_PATH):

    st.error(
        "Prediction file not found:\n\n"
        f"{PREDICTIONS_PATH}"
    )

    st.stop()


df = load_predictions()


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("🔎 Filters")


# Store filter

stores = sorted(
    df["store_nbr"].unique()
)

selected_store = st.sidebar.selectbox(
    "Select Store",
    ["All"] + stores
)


# Family filter

families = sorted(
    df["family"].unique()
)

selected_family = st.sidebar.selectbox(
    "Select Product Family",
    ["All"] + families
)


# Date filter

min_date = df["date"].min().date()
max_date = df["date"].max().date()

selected_dates = st.sidebar.date_input(
    "Select Date Range",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)


# ============================================================
# APPLY FILTERS
# ============================================================

filtered_df = df.copy()


if selected_store != "All":

    filtered_df = filtered_df[
        filtered_df["store_nbr"]
        == selected_store
    ]


if selected_family != "All":

    filtered_df = filtered_df[
        filtered_df["family"]
        == selected_family
    ]


if isinstance(selected_dates, tuple):

    if len(selected_dates) == 2:

        start_date, end_date = selected_dates

        filtered_df = filtered_df[
            (filtered_df["date"].dt.date >= start_date)
            &
            (filtered_df["date"].dt.date <= end_date)
        ]


# ============================================================
# KPI CALCULATIONS
# ============================================================

actual_sales = filtered_df[
    "actual_sales"
].sum()

predicted_sales = filtered_df[
    "predicted_sales"
].sum()

absolute_error = filtered_df[
    "absolute_error"
].mean()


if actual_sales != 0:

    wape = (
        filtered_df["absolute_error"].sum()
        /
        abs(filtered_df["actual_sales"]).sum()
        * 100
    )

else:

    wape = 0


# ============================================================
# KPI CARDS
# ============================================================

st.subheader("📊 Forecast Overview")

col1, col2, col3, col4 = st.columns(4)

with col1:

    st.metric(
        "Actual Sales",
        f"{actual_sales:,.0f}"
    )


with col2:

    st.metric(
        "Predicted Sales",
        f"{predicted_sales:,.0f}"
    )


with col3:

    st.metric(
        "Mean Absolute Error",
        f"{absolute_error:,.2f}"
    )


with col4:

    st.metric(
        "WAPE",
        f"{wape:.2f}%"
    )


# ============================================================
# ACTUAL VS PREDICTED
# ============================================================

st.subheader(
    "📈 Actual vs Predicted Sales"
)


daily = (
    filtered_df
    .groupby("date")
    .agg(
        actual_sales=("actual_sales", "sum"),
        predicted_sales=("predicted_sales", "sum")
    )
    .reset_index()
)

daily = daily.set_index("date")


st.line_chart(
    daily[
        [
            "actual_sales",
            "predicted_sales"
        ]
    ]
)


# ============================================================
# PREDICTION ERROR
# ============================================================

st.subheader("📉 Prediction Error")

error_daily = (
    filtered_df
    .groupby("date")
    ["absolute_error"]
    .mean()
)

st.line_chart(
    error_daily
)


# ============================================================
# STORE PERFORMANCE
# ============================================================

st.subheader("🏪 Store Performance")

store_data = load_csv(
    STORE_PERFORMANCE_PATH
)

if store_data is not None:

    st.dataframe(
        store_data,
        use_container_width=True,
        hide_index=True
    )

else:

    st.info(
        "Store performance file not found."
    )


# ============================================================
# PRODUCT FAMILY PERFORMANCE
# ============================================================

st.subheader(
    "📦 Product Family Performance"
)

family_data = load_csv(
    FAMILY_PERFORMANCE_PATH
)

if family_data is not None:

    st.dataframe(
        family_data,
        use_container_width=True,
        hide_index=True
    )

else:

    st.info(
        "Family performance file not found."
    )


# ============================================================
# MONTHLY PERFORMANCE
# ============================================================

st.subheader(
    "📅 Monthly Performance"
)

monthly_data = load_csv(
    MONTHLY_PERFORMANCE_PATH
)

if monthly_data is not None:

    st.dataframe(
        monthly_data,
        use_container_width=True,
        hide_index=True
    )

else:

    st.info(
        "Monthly performance file not found."
    )


# ============================================================
# MODEL COMPARISON
# ============================================================

st.subheader(
    "🤖 Model Comparison"
)

comparison = load_csv(
    MODEL_COMPARISON_PATH
)

if comparison is not None:

    st.dataframe(
        comparison,
        use_container_width=True,
        hide_index=True
    )

else:

    st.info(
        "Model comparison file not found."
    )


# ============================================================
# OVERALL METRICS
# ============================================================

st.subheader(
    "🎯 Final Model Metrics"
)

metrics = load_csv(
    OVERALL_METRICS_PATH
)

if metrics is not None:

    st.dataframe(
        metrics,
        use_container_width=True,
        hide_index=True
    )

else:

    st.info(
        "Overall metrics file not found."
    )


# ============================================================
# TOP ERRORS
# ============================================================

st.subheader(
    "⚠️ Largest Prediction Errors"
)

top_errors = filtered_df.sort_values(
    "absolute_error",
    ascending=False
).head(20)

st.dataframe(
    top_errors,
    use_container_width=True,
    hide_index=True
)


# ============================================================
# RAW PREDICTIONS
# ============================================================

with st.expander(
    "🔍 View Raw Predictions"
):

    st.dataframe(
        filtered_df,
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Demand Forecasting Project | "
    "Tuned LightGBM Model | "
    "Validation period: May 18, 2017 – August 15, 2017"
)